# Increases the amount of memory Gradle can use and optimizes the GC
	# -XX:+UseZGC
	org.gradle.jvmargs=-Xmx4G
# Helps with build times
	org.gradle.parallel=true
# Caches Dependencies for faster build times.
	org.gradle.caching=true

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
	minecraft_version=26.1-rc-2
	loader_version=0.18.4

# Mod Properties
	mod_id = simple_copper_pipes
	mod_version = 2.1.3
	protocol_version = 2
	maven_group = net.lunade
	archives_base_name = SimpleCopperPipes-mc26.1

# Dependencies
	fabric_api_version=0.143.15+26.1
	frozenlib_version=2.4.1-mc26.1-rc-2
    thecopperierage_version=1.0.6-mc26.1-snapshot-1
	modmenu_version=18.0.0-alpha.5
	cloth_config_version=20.0.149
