modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/simple_copper_pipes/icon.png"
    authors="Lunade/AViewFromTheTop"
    description='''
Adds intuitive and simple-to-understand Copper Pipes to Minecraft.
    '''

[[mixins]]
config="simple_copper_pipes.mixins.json"

[[mixins]]
config="simple_copper_pipes.create.mixins.json"
requiredMods=["create"]

[[ dependencies.simple_copper_pipes ]]
    modId="neoforge"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.simple_copper_pipes ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.simple_copper_pipes ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.simple_copper_pipes ]]
    modId="thecopperierage"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[ dependencies.simple_copper_pipes ]]
    modId="cloth-config"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
